---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Sample VPC'

Resources:
Type: AWS::EKS::Cluster
    Properties:
    Name: prod
    Version: '1.11'
    RoleArn: !ref ClusterRole
    ResourcesVpcConfig:
        SecurityGroupIds: 
        - !ref ClusterControlPlanSecurityGroup
        SubnetIds:
        - Fn::InportValue: testexport-Subnet1subnet-6782e71e
        - subnet-e7e761ac

  ClusterRole:
    Description: Allows EKS to manage clusters on your behalf.
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
            Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  ClusterControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId:
        Fn::ImportValue:
          !Sub "${VPCStack}-VPCID"