apiVersion: v1
kind: Pod
metadata:
  name: pod-secretsmanager
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::794843820546:role/secretsmanager
spec:
  containers:
  - name: pod-secretsmanager
    image: python:latest
    command: ["/bin/sh", "-c"]
    args: ["pip3 install awscli; which aws && sleep 3000"]
    env:
      - name: ENDPOINT
        value: "https://secretsmanager.us-west-2.amazonaws.com"
      - name: REGION
        value: "us-west-2"
      - name: SECRETNAME
        value: "sm-demo-secret"
  restartPolicy: Never